'use strict';
// Local concept interactions. No model requests, uploads, execution or persistent storage.
posts.splice(3,0,{id:'resume-skill',title:'整理了一个改简历的 Skill，文件和用法都在这',desc:'试过几次，主要拿它追问项目细节。别让它编数字，最后一定自己核对。',author:'远山',initial:'远',color:'#e4e9f2',category:'技能学习',tags:['Skill分享','简历准备'],model:'通用方法',rounds:6,likes:146,cover:'skill',reflection:'我发现自己最需要的不是把句子写得更厉害，而是把做过什么、为什么做、结果如何讲清楚。\n\n因此把“先追问、后整理、禁止编造经历”写成了一份方法说明。具体环境对 Skill 的支持不同，也可以直接把方法作为参考资料交给 AI。',skillName:'experience-interviewer',skillContent:'---\nname: experience-interviewer\ndescription: 帮助使用者梳理真实项目经历，通过追问明确个人贡献和证据。\n---\n\n# 项目经历追问\n\n1. 先询问目标岗位和一段真实项目经历。每次只问一个问题。\n2. 依次确认背景、目标、个人行动、结果，以及可以核实的证据。\n3. 不编造指标、职责、学历、任职经历或项目成果。缺失信息明确标记待补充。\n4. 用户确认事实后，提供一版简洁表述，并解释改动。\n5. 最后提出一个可能的面试追问，让用户尝试自己回答。\n',skillUsage:'适合：有真实经历，但不知道怎样讲清楚的人。\n\n1. 下载并阅读 SKILL.md，检查是否适合自己的使用场景。\n2. 在支持自定义 Skill 的工具中，按该工具的说明导入；不支持时，可把文件作为参考资料附给 AI。\n3. 提供目标岗位和一段已脱敏的真实经历，请 AI 按步骤追问。\n4. 核对最后的每项事实，删除你不能证明的结果。\n\n示例输入：“我准备应聘产品岗位，这是我做过的项目。请先通过追问帮我明确个人贡献。”\n\n这份示例只是文字指导，不包含脚本，也不会在来回中执行。',dialogue:[['user','我做过一个小组项目，但不知道怎么写自己的贡献。'],['ai','先讲一件你亲自完成的事情。项目要解决什么问题？'],['user','我负责整理访谈记录，找出了三类重复出现的反馈。'],['ai','你怎样判断它们属于同一类？这些发现后来影响了哪个具体决定？'],['user','有一类是新用户不知道下一步做什么，我们据此修改了引导。没有正式测效果。'],['ai','那就描述真实行动和已发生的改动，不填没有测量的提升数据。可以另外说明后续想怎样验证。']],comments:[['木木','附使用说明比只给文件清楚多了，知道从哪里开始。']]});
activities.splice(2,0,{id:'resume-help',kind:'提问',owner:'木木',title:'第一次找实习，求一份改简历的完整对话',desc:'第一次找实习，不知道怎么把经历讲清楚。有对话、复盘或带说明的 Skill 都欢迎。',people:19,tags:['求助','简历准备','资源征集'],prompt:'我第一次准备实习简历，有课程项目，但写出来总像流水账。\n\n想看看大家和 AI 一起梳理经历、修改表达的完整过程。欢迎贴来回里的分享，上传脱敏对话，或者分享带使用说明的 Skill。\n希望附上适用背景和你觉得最有用的一步。',submissions:[['远山','我把“先追问、后整理”的方法分享在「发现」里了，搜索“简历”可以看到 Skill 和使用说明。']]});
activities.splice(4,0,{id:'exam-help',kind:'提问',owner:'七七',title:'有没有用 AI 复习备考的？想抄抄你们的问法',desc:'解释看着都懂，换一道题又不会了。想看看别人是怎么练的。',people:31,tags:['考试准备','学习方法'],prompt:'我经常看完 AI 的解释觉得懂了，一做题还是不会。\n\n想征集“解释—练习—出错—纠正—独立完成”的对话记录。不同科目都欢迎，也可以分享你自己的练习方法。\n请注明学习背景；没有解决的过程也可以一起讨论。',submissions:[]});
activities.push({id:'missing-painting',kind:'挑战',owner:'白昼推理社',title:'写了个画廊失窃案，看看你几轮能破',desc:'线索和真相都设定好了，可以进来问。破完愿意的话，发出来聊聊你的思路。',people:46,tags:['用户设计','互动叙事','推理游戏'],prompt:'雨夜闭馆后，展厅中央的画消失了。门窗完好，门禁只记录了保安和馆员。现场留下空画框、地上的水迹，以及一本写着“22:10”的值班簿。\n\n你可以调查时间线、询问人物，逐步提出解释。这里只演示几条预设对话分支；正式版本可以由作者编写事实与线索，交给内置模型主持。',submissions:[],privateLogic:'22:10 屋顶漏水，馆员为了保护画作，把画布转移到楼上干燥的修复室。保安知道转移，门禁完整；水迹来自漏水。不是失窃。'});
state.privateSessions=new Map();state.sessionActivity=null;state.sharingSkill=false;
const originalCover=coverHTML;
coverHTML=function(p,detail=false){if(p.cover!=='skill')return originalCover(p,detail);return `<div class="cover skill-cover"><div class="skill-file-icon">${icon('file')}<span>SKILL.md</span></div><h4>改简历用的。<br>文件放这了。</h4><div class="skill-cover-bottom"><span>附使用步骤</span><span>可下载 ${icon('download')}</span></div></div>${detail?'':`<span class="cover-label">${icon('layers')} 技能包分享</span>`}`;};
const baseRender=render;
const designedCover=coverHTML;
coverHTML=function(p,detail=false){if(p.author==='好奇的你'&&!p.image)return `<div class="cover personal-note"><span class="note-kicker">${p.skillContent?'Skill 与使用说明':esc(p.category)} · 我的分享</span><h4>${esc(p.title)}</h4><p>${esc(p.desc)}</p></div>`;return designedCover(p,detail);};
render=function(){const reflectionMode=state.filter==='思考复盘';if(reflectionMode)state.filter='全部';baseRender();if(reflectionMode){state.filter='思考复盘';if(state.page==='discover'){$$('[data-filter]').forEach(b=>b.classList.remove('active'));$('[data-reflections]')?.classList.add('active');$('#feed').innerHTML=feedHTML(posts.filter(matches).filter(p=>p.reflection));}}};
const baseRenderPost=renderPostDetail;
renderPostDetail=function(){baseRenderPost();const p=state.currentPost;if(!p?.skillContent)return;const tabs=$('.detail-tabs');tabs.insertAdjacentHTML('beforeend',`<button class="detail-tab ${state.detailTab==='skill'?'active':''}" data-detail-tab="skill">Skill 与使用说明</button>`);if(state.detailTab==='skill'){$('.conversation,.raw-dialogue,.reflection').outerHTML=`<section class="skill-detail"><div class="skill-download"><span>${icon('file')} SKILL.md</span><button class="primary" data-ext="download-skill">${icon('download')} 下载 Skill</button></div><h3>如何使用</h3><p>${esc(p.skillUsage||'作者尚未提供说明，请先向作者确认适用环境与步骤。')}</p><details><summary>查看文件内容</summary><pre>${esc(p.skillContent)}</pre></details></section>`;}const box=$('.reuse-box');box.innerHTML=`<h3>文件和用法都在这里</h3><p>先看适用背景与使用步骤，再把这个技能包带到自己的 AI 工具中。</p><button class="primary" data-detail-tab="skill">${icon('file')} 查看 Skill 与教程</button><button class="secondary" data-action="reuse">${icon('chat')} 参考这段对话</button>`;};
const baseOpenCompose=openCompose;
openCompose=function(type='share'){state.sharingSkill=false;baseOpenCompose(type);};
const baseRenderCompose=renderCompose;
renderCompose=function(){baseRenderCompose();const share=state.composeType==='share';const d=state.draft;const tabs=$('.compose-tabs');tabs.insertAdjacentHTML('beforeend',`<button class="compose-tab ${state.sharingSkill&&share?'active':''}" data-ext="compose-skill">分享 Skill</button>`);if(state.sharingSkill&&share){$('[data-compose-type="share"]').classList.remove('active');$('.compose-inner h2').textContent='分享 Skill，顺便教教怎么用';}if(share){const anchor=$('.privacy-note');anchor.insertAdjacentHTML('beforebegin',`<details class="skill-upload-details" ${state.sharingSkill?'open':''}><summary>附上 Skill / 方法文件与使用说明</summary><label class="upload-zone">${icon('file')} 导入 SKILL.md（仅读取文字）<input type="file" id="skill-file" accept=".md,.txt"></label><label class="form-field"><span>Skill 内容</span><textarea name="skillContent" id="skill-content-input" rows="4" maxlength="100000" placeholder="粘贴技能说明，或导入文件…" ${state.sharingSkill?'required':''}>${esc(d.skillContent||'')}</textarea></label><label class="form-field"><span>怎么用 <small>环境、步骤、示例输入和适用范围</small></span><textarea name="skillUsage" rows="4" maxlength="10000" placeholder="适合谁？在哪使用？先准备什么？第一句话怎么说？" ${state.sharingSkill?'required':''}>${esc(d.skillUsage||'')}</textarea></label><p class="hint">仅分享文本文件，不在本平台安装或执行。</p></details>`);}else if(state.composeType==='挑战'){const anchor=$('.privacy-note');anchor.insertAdjacentHTML('beforebegin',`<details class="skill-upload-details"><summary>设计主持人的逻辑与线索（可选）</summary><label class="form-field"><span>事实设定、线索顺序、回答规则</span><textarea name="privateLogic" rows="4" maxlength="12000" placeholder="例如：事实真相是什么？哪些线索先出现？什么情况下给提示？">${esc(d.privateLogic||'')}</textarea></label><p class="hint">这些设定不会出现在公开说明里。当前 Demo 全部运行在浏览器中，不能真正保密；正式版本需由服务端独立保管。此处不填写敏感内容。</p></details>`);}};
const baseReview=reviewDraft;
reviewDraft=function(){captureDraft();if(state.draft.skillContent?.trim()&&!state.draft.skillUsage?.trim()){toast('分享 Skill 时，请补充怎么用，方便别人真正用起来。');return;}baseReview();const form=$('#publish-form'),footer=$('.compose-footer',form);for(const [key,label] of [['skillContent','Skill 文件内容'],['skillUsage','使用说明']]){if(state.draft[key]){state.draft[key]=redact(state.draft[key]);footer.insertAdjacentHTML('beforebegin',`<label class="form-field"><span>${label} · 将公开展示</span><textarea name="${key}" rows="4">${esc(state.draft[key])}</textarea></label>`);}}};
const basePublish=publishDraft;
publishDraft=function(form){const type=state.composeType;const d={...state.draft,...Object.fromEntries(new FormData(form).entries())};if(d.skillContent?.trim()&&!d.skillUsage?.trim()){toast('请保留 Skill 的使用说明。');return;}if(!d.title?.trim()||!d.description?.trim()){toast('标题和背景不能只包含空格。');return;}basePublish(form);if(type==='share'&&d.skillContent){const p=posts[0];p.skillContent=d.skillContent;p.skillUsage=d.skillUsage;p.cover=p.image?'photo':'skill';p.skillName='shared-skill';render();renderPostDetail();}if(type==='挑战'&&d.privateLogic)activities[0].privateLogic=d.privateLogic;};
const baseActivityDetail=renderActivityDetail;
renderActivityDetail=function(){baseActivityDetail();const a=state.currentActivity;const side=$('.detail-side');side.insertAdjacentHTML('afterbegin',`<div class="session-entry"><div>${icon('shield')} 先自己探索，再决定是否分享</div><button class="primary" data-ext="start-session">${icon('chat')} ${state.privateSessions.has(a.id)?'继续我的对话':'在这里和 AI 试一试'}</button><p>交互演示 · 预设回复，尚未接入模型</p></div>`);if(a.kind==='提问'){const field=$('#submission-form textarea');field.placeholder='我有一段相关经历 / 对话 / Skill…\n\n适合的背景是…\n使用步骤是…';const upload=$('#submission-file');upload.accept='.md,.txt,audio/*,image/*';upload.parentElement.childNodes.forEach(n=>{if(n.nodeType===3&&n.textContent.trim())n.textContent=' 附上对话、Skill 或创作片段';});}};
function downloadSkill(){const p=state.currentPost;if(!p?.skillContent)return;const url=URL.createObjectURL(new Blob([p.skillContent],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='SKILL.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);toast('Skill 已准备好，请先阅读使用说明与文件内容。');}
function startSession(){const a=state.currentActivity;if(!a)return;state.sessionActivity=a;if(!state.privateSessions.has(a.id)){const initial=a.id==='missing-painting'?'欢迎调查「消失的画」。你可以从水迹、门禁或值班记录入手。这里的回复来自演示脚本，不是真实模型。':a.id==='turtle'?'我们来探索这封没有寄出的信。你可以先问写信的人、收信对象，或者写信的目的。这是开放推理的脚本示例。':`我们一起探索「${a.title}」。先说说你已经知道什么、最想解决哪一步。这是预设回复的体验演示。`;state.privateSessions.set(a.id,[['ai',initial]]);}renderSession();if(!$('#session-dialog').open){$('#session-dialog').showModal();document.body.classList.add('no-scroll');}}
function renderSession(){const a=state.sessionActivity;const turns=state.privateSessions.get(a.id);const suggested=a.id==='missing-painting'?['地上的水从哪里来？','谁在 22:10 进入过展厅？','画是不是被移到修复室了？']:a.id==='turtle'?['写信是为了寄给别人吗？','他是在写给未来的自己吗？','我想看看另一种解释']:['先帮我澄清目标','我想比较两种方案','怎样验证这个想法？'];$('#session-content').innerHTML=`<div class="session-inner"><div class="dialog-top"><div><span class="session-status">${icon('shield')} 仅自己可见 · 本次页面</span><h2>${esc(a.title)}</h2></div><button class="icon-btn" data-close aria-label="关闭我的对话">${icon('close')}</button></div><div class="model-indicator">${icon('spark')} 演示主持 <span>预设回复 · 未接入模型</span></div><div class="session-turns">${turns.map(([role,text])=>`<div class="chat-turn ${role}"><span class="chat-avatar">${role==='user'?'我':'AI'}</span><p>${esc(text)}</p></div>`).join('')}</div><div class="suggested-questions">${suggested.map(s=>`<button data-question="${esc(s)}">${esc(s)}</button>`).join('')}</div><form id="session-form"><label class="session-input"><textarea name="message" required maxlength="2000" placeholder="写下你的问题或想法…" aria-label="给演示主持的消息"></textarea><button class="primary" type="submit" aria-label="发送消息">${icon('arrow')}</button></label></form><div class="session-bottom"><button class="secondary" data-ext="keep-private">先留给自己</button><button class="primary" data-ext="share-session" ${turns.length<2?'disabled':''}>挑选过程，分享给大家</button></div><p class="session-note">对话不会自动公开。你可以先挑选片段、脱敏和复盘，再决定发布；刷新后本次记录清除。</p></div>`;}
function scriptedReply(text,a){if(a.id==='missing-painting'){if(/修复|移到|转移|保护|漏水/.test(text))return '你的解释与本例设定一致：22:10 屋顶漏水，馆员把画布移到楼上的干燥修复室，保安协助。画没有失窃。你可以回看哪些问题帮助你排除了错误假设。';if(/水|地面|地上/.test(text))return '水迹沿着墙角延伸，靠近画作原来悬挂的位置。馆员说当晚下了大雨，展厅天花板有新出现的潮湿痕迹。';if(/谁|22|门禁|时间|保安|馆员/.test(text))return '22:10 馆员刷卡进入，保安随后到场。两人都没有带着画离开建筑；值班簿写着“临时处理，移交楼上”。';if(/框|画布/.test(text))return '画框仍然留在墙上，没有撬动痕迹。固定画布的卡扣被整齐地打开了。';return '这条问题没有配置对应的演示分支。你可以尝试调查地上的水、22:10 的门禁记录，或者提出画去了哪里的解释。正式版本将由模型根据作者设定回答。';}if(a.id==='turtle'){if(/自己|未来/.test(text))return '这是一个自洽的方向：写给未来的自己，后来收到曾经寄存的旧信。这个开放示例不判唯一答案，你还可以检验为什么“收到信”会让他停止写。';if(/别人|寄|目的/.test(text))return '在这个演示分支里，写信的目的不是即时联络别人，而是等待一个未来时刻。你可以继续问收信对象。';return '这里演示如何围绕谜面追问，未设置真实 AI 主持或唯一谜底。可以试着区分写信目的、收信对象和停止写信的原因。';}if(/目标|澄清/.test(text))return '可以先明确三个条件：你希望完成什么、已经有哪些材料、有哪些时间或能力限制。你最希望这次对话帮你推进哪一步？（预设演示回复）';if(/比较|方案/.test(text))return '先把两个方案写出来，再用同一组标准比较：是否解决目标、成本多大、怎样验证。不要只比较描述是否好听。（预设演示回复）';if(/验证|测试/.test(text))return '找一个最小的可观察结果：用一个具体例子试做，记录预期和实际差异，再决定是否继续。你能在今天完成哪个小验证？（预设演示回复）';return '收到你的想法。当前 Demo 不会真正理解或分析它，可以点击上方示例追问，体验对话如何积累以及如何选择分享。正式版本会在接入模型后，根据材料和上下文回复。';}
function sendSession(text){text=text.trim();if(!text)return;const a=state.sessionActivity;state.privateSessions.get(a.id).push(['user',text],['ai',scriptedReply(text,a)]);renderSession();$('.session-turns').scrollTop=$('.session-turns').scrollHeight;}
function shareSession(){const a=state.sessionActivity;const turns=state.privateSessions.get(a.id);closeDialog($('#session-dialog'));if($('#detail-dialog').open)closeDialog($('#detail-dialog'));openCompose('share');state.draft={title:`我的探索：${a.title}`,description:'在这次探索中，我尝试了这些问题。',category:a.kind==='共创'?'创作记录':'技能学习',tags:a.tags.join('，'),dialogue:'【本段来自来回 Demo 的预设回复演示，不是真实模型对话】\n\n'+turns.map(([r,t])=>`${r==='user'?'我':'演示主持'}：${t}`).join('\n\n'),reflection:''};renderCompose();toast('可以删掉不想公开的片段，补上复盘，再检查发布。');}
$('#session-dialog').addEventListener('close',()=>{if(!$$('dialog[open]').length)document.body.classList.remove('no-scroll');});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-question')){sendSession(b.dataset.question);return;}if(b.dataset.composeType){state.sharingSkill=false;renderCompose();return;}switch(b.dataset.ext){case'compose-skill':captureDraft();state.composeType='share';state.sharingSkill=true;renderCompose();break;case'download-skill':downloadSkill();break;case'start-session':startSession();break;case'keep-private':closeDialog($('#session-dialog'));toast('对话仍仅自己可见，可以从活动页继续。');if(state.currentActivity)renderActivityDetail();break;case'share-session':shareSession();break;}});
document.addEventListener('submit',e=>{if(e.target.id==='session-form'){e.preventDefault();if(e.target.reportValidity())sendSession(e.target.elements.message.value);}});
document.addEventListener('change',async e=>{if(e.target.id!=='skill-file')return;const file=e.target.files?.[0];if(!file)return;if(!/\.(md|txt)$/i.test(file.name)||file.size>500000){toast('请使用 500 KB 以内的 Markdown 或 TXT 文件。');e.target.value='';return;}try{const text=await file.text();if(text.length>100000){toast('文件过长，请保留 10 万字符以内。');return;}$('#skill-content-input').value=text;toast('已读取方法文件，请补充使用说明。');}catch{toast('读取失败，请重新选择文件。');}});
render();
